package com.vbteam.views;

import com.vbteam.services.socket.ConnectionService;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author BatuPC
 */
public class FrmAuth extends javax.swing.JFrame {

    CardLayout cardLayout;
    private int pX, pY;
    private ConnectionService conService;

    public FrmAuth() {
        //Remove Title Bar
        setUndecorated(true);
        initComponents();

        //Server Connection Credintials
        conService = new ConnectionService("localhost");

        //Lacivert Arkaplan Renk Kodu 
        pnl_auth.setBackground(new Color(221, 119, 23));

        centerLocation();
        //setLocationRelativeTo(null);

        //Card layout
        cardLayout = (CardLayout) pnl_cardLayout.getLayout();

        //Özelleştirilmiş kapatma butonu
        btn_close.addActionListener(new CloseListener());

        /*
        Özelleştirilmiş Title Barının hareket kabiliyeti
         */
        pnl_titlebar.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                pX = e.getX();
                pY = e.getY();
            }
        });

        pnl_titlebar.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                setLocation(evt.getXOnScreen() - pX, evt.getYOnScreen() - pY);

            }
        });

    }

    private void centerLocation() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * Uygulamayı Kapatma metodu
     */
    private class CloseListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titlebar = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        pnl_cardLayout = new javax.swing.JPanel();
        pnl_main = new javax.swing.JPanel();
        pnl_main_left = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        pnl_main_right = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        btn_auth = new javax.swing.JButton();
        pnl_auth = new javax.swing.JPanel();
        pnl_register = new javax.swing.JPanel();
        txt_registerUsername = new javax.swing.JTextField();
        lbl_register = new javax.swing.JLabel();
        separator_username = new javax.swing.JSeparator();
        separator_password_register = new javax.swing.JSeparator();
        btn_register = new javax.swing.JButton();
        separator_password_control = new javax.swing.JSeparator();
        pw_register_control = new javax.swing.JPasswordField();
        pw_register = new javax.swing.JPasswordField();
        btn_cardMenu = new javax.swing.JButton();
        pnl_login = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        txt_loginUsername = new javax.swing.JTextField();
        separator_login = new javax.swing.JSeparator();
        pw_login = new javax.swing.JPasswordField();
        separator_password_login = new javax.swing.JSeparator();
        btn_login = new javax.swing.JButton();
        pnl_mainscreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 16, 60));

        pnl_titlebar.setBackground(new java.awt.Color(45, 48, 53));

        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("X");
        btn_close.setToolTipText("");
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);

        javax.swing.GroupLayout pnl_titlebarLayout = new javax.swing.GroupLayout(pnl_titlebar);
        pnl_titlebar.setLayout(pnl_titlebarLayout);
        pnl_titlebarLayout.setHorizontalGroup(
            pnl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_titlebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_titlebarLayout.setVerticalGroup(
            pnl_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        pnl_cardLayout.setForeground(new java.awt.Color(255, 204, 102));
        pnl_cardLayout.setLayout(new java.awt.CardLayout());

        pnl_main.setPreferredSize(new java.awt.Dimension(1366, 768));

        pnl_main_left.setBackground(new java.awt.Color(37, 40, 44));

        logo.setBackground(new java.awt.Color(37, 40, 44));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon("D:\\Resimler\\Design\\vblogowhite.png")); // NOI18N

        javax.swing.GroupLayout pnl_main_leftLayout = new javax.swing.GroupLayout(pnl_main_left);
        pnl_main_left.setLayout(pnl_main_leftLayout);
        pnl_main_leftLayout.setHorizontalGroup(
            pnl_main_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_main_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 558, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnl_main_leftLayout.setVerticalGroup(
            pnl_main_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_main_leftLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        pnl_main_right.setBackground(new java.awt.Color(45, 48, 53));

        lbl_welcome.setBackground(new java.awt.Color(167, 168, 171));
        lbl_welcome.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(167, 168, 171));
        lbl_welcome.setText("Mail Uygulamasına Hoş geldiniz !");

        btn_auth.setText("Kayıt Ol / Giriş Yap");
        btn_auth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_authActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_main_rightLayout = new javax.swing.GroupLayout(pnl_main_right);
        pnl_main_right.setLayout(pnl_main_rightLayout);
        pnl_main_rightLayout.setHorizontalGroup(
            pnl_main_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_main_rightLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(pnl_main_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_auth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        pnl_main_rightLayout.setVerticalGroup(
            pnl_main_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_main_rightLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lbl_welcome)
                .addGap(178, 178, 178)
                .addComponent(btn_auth, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addComponent(pnl_main_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_main_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_main_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_cardLayout.add(pnl_main, "welcome");

        pnl_register.setBackground(new java.awt.Color(37, 40, 44));

        txt_registerUsername.setBackground(new java.awt.Color(37, 40, 44));
        txt_registerUsername.setForeground(new java.awt.Color(255, 255, 255));
        txt_registerUsername.setText("Username");
        txt_registerUsername.setBorder(null);

        lbl_register.setBackground(new java.awt.Color(167, 168, 171));
        lbl_register.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lbl_register.setForeground(new java.awt.Color(167, 168, 171));
        lbl_register.setText("Kayıt Ol !");

        separator_username.setBackground(new java.awt.Color(255, 255, 255));
        separator_username.setForeground(new java.awt.Color(255, 255, 255));

        separator_password_register.setBackground(new java.awt.Color(255, 255, 255));
        separator_password_register.setForeground(new java.awt.Color(255, 255, 255));

        btn_register.setText("Kayıt ol");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        separator_password_control.setBackground(new java.awt.Color(255, 255, 255));
        separator_password_control.setForeground(new java.awt.Color(255, 255, 255));

        pw_register_control.setBackground(new java.awt.Color(37, 40, 44));
        pw_register_control.setForeground(new java.awt.Color(255, 255, 255));
        pw_register_control.setText("password");
        pw_register_control.setBorder(null);

        pw_register.setBackground(new java.awt.Color(37, 40, 44));
        pw_register.setForeground(new java.awt.Color(255, 255, 255));
        pw_register.setText("password");
        pw_register.setBorder(null);

        btn_cardMenu.setForeground(new java.awt.Color(255, 255, 255));
        btn_cardMenu.setText("<");
        btn_cardMenu.setToolTipText("");
        btn_cardMenu.setBorderPainted(false);
        btn_cardMenu.setContentAreaFilled(false);
        btn_cardMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cardMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_registerLayout = new javax.swing.GroupLayout(pnl_register);
        pnl_register.setLayout(pnl_registerLayout);
        pnl_registerLayout.setHorizontalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerLayout.createSequentialGroup()
                .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_registerLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(separator_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_registerUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separator_password_register)
                            .addComponent(pw_register_control)
                            .addComponent(separator_password_control)
                            .addComponent(pw_register, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))
                    .addComponent(btn_cardMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registerLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(lbl_register)
                .addGap(248, 248, 248))
        );
        pnl_registerLayout.setVerticalGroup(
            pnl_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registerLayout.createSequentialGroup()
                .addComponent(btn_cardMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lbl_register)
                .addGap(115, 115, 115)
                .addComponent(txt_registerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator_username, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pw_register, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator_password_register, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pw_register_control, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator_password_control, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pnl_login.setBackground(new java.awt.Color(45, 48, 53));

        lbl_login.setBackground(new java.awt.Color(167, 168, 171));
        lbl_login.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(167, 168, 171));
        lbl_login.setText("Giriş Yap !");
        lbl_login.setAlignmentY(0.3F);

        txt_loginUsername.setBackground(new java.awt.Color(45, 48, 53));
        txt_loginUsername.setForeground(new java.awt.Color(255, 255, 255));
        txt_loginUsername.setText("Username");
        txt_loginUsername.setBorder(null);

        separator_login.setBackground(new java.awt.Color(255, 255, 255));
        separator_login.setForeground(new java.awt.Color(255, 255, 255));

        pw_login.setBackground(new java.awt.Color(45, 48, 53));
        pw_login.setForeground(new java.awt.Color(255, 255, 255));
        pw_login.setText("password");
        pw_login.setBorder(null);
        pw_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_loginActionPerformed(evt);
            }
        });

        separator_password_login.setBackground(new java.awt.Color(255, 255, 255));
        separator_password_login.setForeground(new java.awt.Color(255, 255, 255));

        btn_login.setText("Giriş Yap");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(lbl_login)
                .addGap(279, 279, 279))
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(pw_login)
                    .addComponent(separator_password_login)
                    .addComponent(txt_loginUsername)
                    .addComponent(separator_login))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lbl_login)
                .addGap(153, 153, 153)
                .addComponent(txt_loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator_login, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pw_login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_authLayout = new javax.swing.GroupLayout(pnl_auth);
        pnl_auth.setLayout(pnl_authLayout);
        pnl_authLayout.setHorizontalGroup(
            pnl_authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_authLayout.createSequentialGroup()
                .addComponent(pnl_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_authLayout.setVerticalGroup(
            pnl_authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_cardLayout.add(pnl_auth, "register");

        javax.swing.GroupLayout pnl_mainscreenLayout = new javax.swing.GroupLayout(pnl_mainscreen);
        pnl_mainscreen.setLayout(pnl_mainscreenLayout);
        pnl_mainscreenLayout.setHorizontalGroup(
            pnl_mainscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnl_mainscreenLayout.setVerticalGroup(
            pnl_mainscreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        pnl_cardLayout.add(pnl_mainscreen, "pnl_login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pw_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_loginActionPerformed

    private void btn_cardMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cardMenuActionPerformed
        cardLayout.show(pnl_cardLayout, "welcome");
    }//GEN-LAST:event_btn_cardMenuActionPerformed

    private void btn_authActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_authActionPerformed
        new Thread(){
            @Override
            public void run(){
                try{
                    conService.connectServer();
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
            }
        }.start();
        if(conService.checkConnection())
            cardLayout.show(pnl_cardLayout, "register");
    }//GEN-LAST:event_btn_authActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_auth;
    private javax.swing.JButton btn_cardMenu;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pnl_auth;
    private javax.swing.JPanel pnl_cardLayout;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_main_left;
    private javax.swing.JPanel pnl_main_right;
    private javax.swing.JPanel pnl_mainscreen;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JPanel pnl_titlebar;
    private javax.swing.JPasswordField pw_login;
    private javax.swing.JPasswordField pw_register;
    private javax.swing.JPasswordField pw_register_control;
    private javax.swing.JSeparator separator_login;
    private javax.swing.JSeparator separator_password_control;
    private javax.swing.JSeparator separator_password_login;
    private javax.swing.JSeparator separator_password_register;
    private javax.swing.JSeparator separator_username;
    private javax.swing.JTextField txt_loginUsername;
    private javax.swing.JTextField txt_registerUsername;
    // End of variables declaration//GEN-END:variables
}
