/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vbteam.views;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author BatuPC
 */
public class FrmDialog extends javax.swing.JFrame {

    int pX, pY;
    FrmDashboard dashboardFrame;
    String actionType;

    public FrmDialog() {
        initComponents();
        move();
        this.setLocationRelativeTo(null);

        this.setBackground(new Color(0, 0, 0, 0));

        //this.setAlwaysOnTop(true);
        btn_first.setVisible(false);
    }

    public void move() {
        this.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                pX = e.getX();
                pY = e.getY();
            }
        });

        this.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                setLocation(evt.getXOnScreen() - pX, evt.getYOnScreen() - pY);
            }
        });
    }

    public void attachDialogToFrame(FrmDashboard _dashboardFrame) {
        dashboardFrame = _dashboardFrame;
    }

    public void setIcon(String type) {
        if (type.equals("confirm")) {
            btn_first.setVisible(false);
            btn_second.setText("OK");
            btn_second.setVisible(true);
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/confirm.png")));
        }
        if (type.equals("error")) {
            btn_first.setVisible(false);

            btn_second.setText("OK");
            btn_second.setVisible(true);
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/cancel.png")));
        }
        if (type.equals("wait")) {
            btn_first.setVisible(false);

            btn_second.setText("OK");
            btn_second.setVisible(false);
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/time-left.png")));
        }
        if (type.equals("boolean")) {
            btn_first.setVisible(true);
            btn_second.setVisible(true);

            btn_first.setText("Evet");
            btn_second.setText("Hayır");

            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/new-email.png")));

        }
    }

    public void setActionType(String text) {
        actionType = text;
    }

    public void setMessage(String message) {
        text.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        btn_first = new javax.swing.JButton();
        btn_second = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/confirm.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 130, 70));

        text.setForeground(new java.awt.Color(238, 217, 217));
        text.setText("Password Incorrect");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 160, 400, 60));

        btn_first.setForeground(new java.awt.Color(0, 0, 0));
        btn_first.setText("OK");
        btn_first.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_firstMouseClicked(evt);
            }
        });
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });
        getContentPane().add(btn_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 40));

        btn_second.setForeground(new java.awt.Color(0, 0, 0));
        btn_second.setText("OK");
        btn_second.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_secondMouseClicked(evt);
            }
        });
        getContentPane().add(btn_second, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 70, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/rect.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_firstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_firstMouseClicked
        setVisible(false);
        if (dashboardFrame != null) {
            dashboardFrame.dialogControl(actionType);
            dashboardFrame.mailPanelState = null;
        }
    }//GEN-LAST:event_btn_firstMouseClicked

    private void btn_secondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_secondMouseClicked
        setVisible(false);
        if (dashboardFrame != null) {
            dashboardFrame.mailPanelState = null;
        }
    }//GEN-LAST:event_btn_secondMouseClicked

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_second;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
