/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vbteam.views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author BatuPC
 */
public class FrmMail extends javax.swing.JFrame {

    boolean maxCheck = false;
    private int pX, pY;

    public FrmMail() {
        initGui();
        initComponents();
        centerLocationAndSetSize();
        moveTitlebar();
    }

    private void centerLocationAndSetSize() {
        this.setSize(1366, 768);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    private void initGui() {
        this.setUndecorated(true); // title barı kaldırıyor
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    public void moveTitlebar() {
        pnl_main_titlebar.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                pX = e.getX() + 160;
                pY = e.getY();
            }
        });

        pnl_main_titlebar.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                setLocation(evt.getXOnScreen() - pX, evt.getYOnScreen() - pY);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        pnl_titlebuttons = new javax.swing.JPanel();
        pnl_btnclose = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        pnl_btnminimize = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JButton();
        pnl_btnmaximize = new javax.swing.JPanel();
        btn_maximize = new javax.swing.JButton();
        pnl_sidebar_menus = new javax.swing.JPanel();
        pnl_sidebar_text = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnl_sidebar_gelen = new javax.swing.JPanel();
        pnl_gelen_icon = new javax.swing.JPanel();
        gelen_icon = new javax.swing.JButton();
        pnl_gelen_text = new javax.swing.JPanel();
        gelen_text = new javax.swing.JLabel();
        pnl_sidebar_giden = new javax.swing.JPanel();
        pnl_giden_icon = new javax.swing.JPanel();
        giden_icon = new javax.swing.JButton();
        pnl_giden_text = new javax.swing.JPanel();
        giden_text = new javax.swing.JLabel();
        pnl_main = new javax.swing.JPanel();
        pnl_main_titlebar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        pnl_sidebar.setBackground(new java.awt.Color(43, 49, 68));
        pnl_sidebar.setPreferredSize(new java.awt.Dimension(160, 0));
        pnl_sidebar.setLayout(new java.awt.BorderLayout());

        pnl_titlebuttons.setBackground(new java.awt.Color(43, 49, 68));
        pnl_titlebuttons.setPreferredSize(new java.awt.Dimension(200, 30));
        pnl_titlebuttons.setLayout(new java.awt.BorderLayout());

        pnl_btnclose.setBackground(new java.awt.Color(37, 40, 44));
        pnl_btnclose.setToolTipText("");
        pnl_btnclose.setPreferredSize(new java.awt.Dimension(55, 0));
        pnl_btnclose.setLayout(new java.awt.BorderLayout());

        btn_close.setBackground(new java.awt.Color(51, 53, 65));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/dry-clean.png"))); // NOI18N
        btn_close.setBorder(null);
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        pnl_btnclose.add(btn_close, java.awt.BorderLayout.CENTER);

        pnl_titlebuttons.add(pnl_btnclose, java.awt.BorderLayout.LINE_START);

        pnl_btnminimize.setBackground(new java.awt.Color(37, 40, 44));
        pnl_btnminimize.setPreferredSize(new java.awt.Dimension(55, 0));
        pnl_btnminimize.setLayout(new java.awt.BorderLayout());

        btn_minimize.setBackground(new java.awt.Color(51, 53, 65));
        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/dry-clean-green.png"))); // NOI18N
        btn_minimize.setBorderPainted(false);
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseExited(evt);
            }
        });
        pnl_btnminimize.add(btn_minimize, java.awt.BorderLayout.CENTER);

        pnl_titlebuttons.add(pnl_btnminimize, java.awt.BorderLayout.LINE_END);

        pnl_btnmaximize.setBackground(new java.awt.Color(37, 40, 44));
        pnl_btnmaximize.setLayout(new java.awt.BorderLayout());

        btn_maximize.setBackground(new java.awt.Color(37, 40, 44));
        btn_maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/dry-clean-yellow.png"))); // NOI18N
        btn_maximize.setToolTipText("");
        btn_maximize.setBorderPainted(false);
        btn_maximize.setContentAreaFilled(false);
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseExited(evt);
            }
        });
        pnl_btnmaximize.add(btn_maximize, java.awt.BorderLayout.CENTER);

        pnl_titlebuttons.add(pnl_btnmaximize, java.awt.BorderLayout.CENTER);

        pnl_sidebar.add(pnl_titlebuttons, java.awt.BorderLayout.PAGE_START);

        pnl_sidebar_menus.setBackground(new java.awt.Color(37, 40, 44));
        pnl_sidebar_menus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_sidebar_text.setBackground(new java.awt.Color(37, 40, 44));
        pnl_sidebar_text.setPreferredSize(new java.awt.Dimension(100, 110));
        pnl_sidebar_text.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/email.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        pnl_sidebar_text.add(jButton1, java.awt.BorderLayout.CENTER);

        pnl_sidebar_menus.add(pnl_sidebar_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        pnl_sidebar_gelen.setBackground(new java.awt.Color(37, 40, 44));
        pnl_sidebar_gelen.setLayout(new java.awt.BorderLayout());

        pnl_gelen_icon.setBackground(new java.awt.Color(37, 40, 44));
        pnl_gelen_icon.setLayout(new java.awt.BorderLayout());

        gelen_icon.setBackground(new java.awt.Color(37, 40, 44));
        gelen_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/mail_menu_icon.png"))); // NOI18N
        gelen_icon.setBorderPainted(false);
        gelen_icon.setContentAreaFilled(false);
        pnl_gelen_icon.add(gelen_icon, java.awt.BorderLayout.LINE_START);

        pnl_sidebar_gelen.add(pnl_gelen_icon, java.awt.BorderLayout.LINE_START);

        pnl_gelen_text.setBackground(new java.awt.Color(37, 40, 44));
        pnl_gelen_text.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_gelen_text.setLayout(new java.awt.BorderLayout());

        gelen_text.setBackground(new java.awt.Color(37, 40, 44));
        gelen_text.setForeground(new java.awt.Color(255, 255, 255));
        gelen_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gelen_text.setText("Gelen Kutusu");
        gelen_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_gelen_text.add(gelen_text, java.awt.BorderLayout.CENTER);

        pnl_sidebar_gelen.add(pnl_gelen_text, java.awt.BorderLayout.LINE_END);

        pnl_sidebar_menus.add(pnl_sidebar_gelen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 40));

        pnl_sidebar_giden.setBackground(new java.awt.Color(37, 40, 44));
        pnl_sidebar_giden.setLayout(new java.awt.BorderLayout());

        pnl_giden_icon.setBackground(new java.awt.Color(37, 40, 44));
        pnl_giden_icon.setPreferredSize(new java.awt.Dimension(60, 60));
        pnl_giden_icon.setLayout(new java.awt.BorderLayout());

        giden_icon.setBackground(new java.awt.Color(37, 40, 44));
        giden_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/mail_menu_icon_giden.png"))); // NOI18N
        giden_icon.setBorder(null);
        giden_icon.setBorderPainted(false);
        giden_icon.setContentAreaFilled(false);
        pnl_giden_icon.add(giden_icon, java.awt.BorderLayout.CENTER);

        pnl_sidebar_giden.add(pnl_giden_icon, java.awt.BorderLayout.LINE_START);

        pnl_giden_text.setBackground(new java.awt.Color(37, 40, 44));
        pnl_giden_text.setPreferredSize(new java.awt.Dimension(120, 0));
        pnl_giden_text.setLayout(new java.awt.BorderLayout());

        giden_text.setForeground(new java.awt.Color(255, 255, 255));
        giden_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giden_text.setText("Giden Kutusu");
        pnl_giden_text.add(giden_text, java.awt.BorderLayout.CENTER);

        pnl_sidebar_giden.add(pnl_giden_text, java.awt.BorderLayout.LINE_END);

        pnl_sidebar_menus.add(pnl_sidebar_giden, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        pnl_sidebar.add(pnl_sidebar_menus, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_sidebar, java.awt.BorderLayout.LINE_START);

        pnl_main.setBackground(new java.awt.Color(56, 58, 71));
        pnl_main.setLayout(new java.awt.BorderLayout());

        pnl_main_titlebar.setBackground(new java.awt.Color(37, 40, 44));
        pnl_main_titlebar.setPreferredSize(new java.awt.Dimension(0, 30));

        javax.swing.GroupLayout pnl_main_titlebarLayout = new javax.swing.GroupLayout(pnl_main_titlebar);
        pnl_main_titlebar.setLayout(pnl_main_titlebarLayout);
        pnl_main_titlebarLayout.setHorizontalGroup(
            pnl_main_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_main_titlebarLayout.setVerticalGroup(
            pnl_main_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_main.add(pnl_main_titlebar, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnl_main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hoverColor(JPanel jpanel, Color color) {
        jpanel.setBackground(color);
    }

    private void btn_maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseEntered
        hoverColor(pnl_btnmaximize, new Color(56,58,71));
    }//GEN-LAST:event_btn_maximizeMouseEntered

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
        maxCheck = !maxCheck;
        if (maxCheck) {
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            double width = screenSize.getWidth();
            double height = screenSize.getHeight();
            this.setLocation(0, 0);
            this.setSize((int) width, (int) height - 40);
        } else {
            centerLocationAndSetSize();
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseExited
        hoverColor(pnl_btnmaximize, new Color(37,40,44));
    }//GEN-LAST:event_btn_maximizeMouseExited

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        hoverColor(pnl_btnclose, new Color(56,58,71));
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        hoverColor(pnl_btnclose, new Color(37,40,44));
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseEntered
        hoverColor(pnl_btnminimize, new Color(56,58,71));
    }//GEN-LAST:event_btn_minimizeMouseEntered

    private void btn_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseExited
        hoverColor(pnl_btnminimize, new Color(37,40,44));
    }//GEN-LAST:event_btn_minimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_maximize;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton gelen_icon;
    private javax.swing.JLabel gelen_text;
    private javax.swing.JButton giden_icon;
    private javax.swing.JLabel giden_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnl_btnclose;
    private javax.swing.JPanel pnl_btnmaximize;
    private javax.swing.JPanel pnl_btnminimize;
    private javax.swing.JPanel pnl_gelen_icon;
    private javax.swing.JPanel pnl_gelen_text;
    private javax.swing.JPanel pnl_giden_icon;
    private javax.swing.JPanel pnl_giden_text;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_main_titlebar;
    private javax.swing.JPanel pnl_sidebar;
    private javax.swing.JPanel pnl_sidebar_gelen;
    private javax.swing.JPanel pnl_sidebar_giden;
    private javax.swing.JPanel pnl_sidebar_menus;
    private javax.swing.JPanel pnl_sidebar_text;
    private javax.swing.JPanel pnl_titlebuttons;
    // End of variables declaration//GEN-END:variables
}
