/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vbteam.views;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author BatuPC
 */
public class FrmTestAuth extends javax.swing.JFrame implements MouseListener {

    private int pX, pY;
    CardLayout mainLayout,registerLayout;

    public FrmTestAuth() {
        setUndecorated(true);
        initComponents();
        moveTitlebar();
        setListeners();
        setLocationRelativeTo(null);
        this.setSize(1366, 768);

        mainLayout = (CardLayout) cardPanel.getLayout();
        registerLayout = (CardLayout) register_screen.getLayout();
    }

    public void hoverColor(Component jpanel, Color color) {
        jpanel.setBackground(color);
    }

    private void setListeners() {
        pnl_login.addMouseListener(this);
        pnl_register.addMouseListener(this);
        pnl_login_arrow.addMouseListener(this);
        pnl_register_username_arrow.addMouseListener(this);
    }

    public void moveTitlebar() {
        cardPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2 && !evt.isConsumed()) {
                    evt.consume();
                    //maximize();
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                pX = e.getX();
                pY = e.getY();
            }
        });

        cardPanel.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                setLocation(evt.getXOnScreen() - pX, evt.getYOnScreen() - pY);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        home_card = new javax.swing.JPanel();
        home_panel = new javax.swing.JPanel();
        home_screen = new javax.swing.JPanel();
        home_Buttons = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        pnl_register = new javax.swing.JPanel();
        lbl_register = new javax.swing.JLabel();
        home_Logo = new javax.swing.JPanel();
        home_logo = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();
        register_card = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        register_screen = new javax.swing.JPanel();
        register_username = new javax.swing.JPanel();
        register_username_input = new javax.swing.JPanel();
        register_username_label = new javax.swing.JLabel();
        register_field_username = new javax.swing.JTextField();
        register_seperator_username = new javax.swing.JSeparator();
        pnl_register_username_arrow = new javax.swing.JPanel();
        lbl_register_username_arrow = new javax.swing.JLabel();
        pnl_progress = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        register_username_logo = new javax.swing.JPanel();
        lbl_register_username_logo = new javax.swing.JLabel();
        register_password = new javax.swing.JPanel();
        register_password_input = new javax.swing.JPanel();
        register_password_label_check = new javax.swing.JLabel();
        register_field_password = new javax.swing.JTextField();
        register_seperator_password = new javax.swing.JSeparator();
        pnl_register_password_arrow = new javax.swing.JPanel();
        lbl_register_password_arrow = new javax.swing.JLabel();
        pnl_progress_password = new javax.swing.JPanel();
        register_field_password_check = new javax.swing.JTextField();
        register_seperator_password_check = new javax.swing.JSeparator();
        register_password_label = new javax.swing.JLabel();
        register_password_logo = new javax.swing.JPanel();
        lbl_register_password_logo = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        login_card = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        login_screen = new javax.swing.JPanel();
        login_logo_panel = new javax.swing.JPanel();
        login_logo = new javax.swing.JLabel();
        login_inputs = new javax.swing.JPanel();
        separator_username = new javax.swing.JSeparator();
        login_username_label = new javax.swing.JLabel();
        login_password_label = new javax.swing.JLabel();
        login_field_username = new javax.swing.JTextField();
        login_field_password = new javax.swing.JPasswordField();
        separator_password = new javax.swing.JSeparator();
        pnl_login_arrow = new javax.swing.JPanel();
        lbl_login_arrow = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardPanel.setLayout(new java.awt.CardLayout());

        home_card.setLayout(new java.awt.BorderLayout());

        home_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_screen.setOpaque(false);
        home_screen.setLayout(new java.awt.BorderLayout());

        home_Buttons.setBackground(new java.awt.Color(31, 31, 31));
        home_Buttons.setOpaque(false);
        home_Buttons.setPreferredSize(new java.awt.Dimension(1370, 70));
        home_Buttons.setLayout(new java.awt.BorderLayout());

        pnl_login.setBackground(new java.awt.Color(30, 29, 32));
        pnl_login.setOpaque(false);
        pnl_login.setPreferredSize(new java.awt.Dimension(690, 15));
        pnl_login.setLayout(new java.awt.BorderLayout());

        lbl_login.setBackground(new java.awt.Color(31, 31, 31));
        lbl_login.setForeground(new java.awt.Color(165, 165, 172));
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Giriş Yap");
        lbl_login.setPreferredSize(new java.awt.Dimension(700, 15));
        pnl_login.add(lbl_login, java.awt.BorderLayout.LINE_START);

        home_Buttons.add(pnl_login, java.awt.BorderLayout.LINE_START);

        pnl_register.setBackground(new java.awt.Color(30, 29, 32));
        pnl_register.setOpaque(false);
        pnl_register.setPreferredSize(new java.awt.Dimension(680, 15));
        pnl_register.setLayout(new java.awt.BorderLayout());

        lbl_register.setBackground(new java.awt.Color(30, 29, 32));
        lbl_register.setForeground(new java.awt.Color(165, 165, 172));
        lbl_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register.setText("Kayıt Ol");
        lbl_register.setPreferredSize(new java.awt.Dimension(690, 15));
        pnl_register.add(lbl_register, java.awt.BorderLayout.LINE_END);

        home_Buttons.add(pnl_register, java.awt.BorderLayout.LINE_END);

        home_screen.add(home_Buttons, java.awt.BorderLayout.PAGE_END);

        home_Logo.setOpaque(false);
        home_Logo.setLayout(new java.awt.BorderLayout());

        home_logo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        home_logo.setForeground(new java.awt.Color(165, 165, 172));
        home_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/vblogowhite.png"))); // NOI18N
        home_logo.setText("Veysel ve Batu Mail Projesi");
        home_logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_logo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home_Logo.add(home_logo, java.awt.BorderLayout.CENTER);

        home_screen.add(home_Logo, java.awt.BorderLayout.CENTER);

        home_panel.add(home_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        background1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/mailbackground.png"))); // NOI18N
        background1.setPreferredSize(new java.awt.Dimension(1366, 768));
        home_panel.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1370, 860));

        home_card.add(home_panel, java.awt.BorderLayout.CENTER);

        cardPanel.add(home_card, "home");

        register_card.setLayout(new java.awt.BorderLayout());

        register_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_screen.setOpaque(false);
        register_screen.setLayout(new java.awt.CardLayout());

        register_username.setOpaque(false);
        register_username.setLayout(new java.awt.BorderLayout());

        register_username_input.setBackground(new java.awt.Color(20, 20, 22));
        register_username_input.setOpaque(false);
        register_username_input.setPreferredSize(new java.awt.Dimension(500, 500));
        register_username_input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_username_label.setForeground(new java.awt.Color(165, 165, 172));
        register_username_label.setText("Kullanıcı Adı");
        register_username_input.add(register_username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        register_field_username.setBackground(new java.awt.Color(20, 20, 22));
        register_field_username.setForeground(new java.awt.Color(255, 255, 255));
        register_field_username.setBorder(null);
        register_username_input.add(register_field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 220, 40));

        register_seperator_username.setBackground(new java.awt.Color(25, 25, 28));
        register_seperator_username.setForeground(new java.awt.Color(25, 25, 28));
        register_username_input.add(register_seperator_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 220, 40));

        pnl_register_username_arrow.setBackground(new java.awt.Color(30, 29, 32));
        pnl_register_username_arrow.setOpaque(false);
        pnl_register_username_arrow.setLayout(new java.awt.BorderLayout());

        lbl_register_username_arrow.setBackground(new java.awt.Color(30, 29, 32));
        lbl_register_username_arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_username_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/right-arrow.png"))); // NOI18N
        lbl_register_username_arrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_register_username_arrow.add(lbl_register_username_arrow, java.awt.BorderLayout.CENTER);

        register_username_input.add(pnl_register_username_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 60, 60));

        pnl_progress.setOpaque(false);
        pnl_progress.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 450));
        pnl_progress.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(450, 450));
        pnl_progress.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(450, 450));
        pnl_progress.add(jPanel3, java.awt.BorderLayout.LINE_END);

        register_username_input.add(pnl_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1370, 70));

        register_username.add(register_username_input, java.awt.BorderLayout.PAGE_END);

        register_username_logo.setOpaque(false);
        register_username_logo.setLayout(new java.awt.BorderLayout());

        lbl_register_username_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_username_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/vblogowhite.png"))); // NOI18N
        lbl_register_username_logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbl_register_username_logo.setPreferredSize(new java.awt.Dimension(300, 300));
        register_username_logo.add(lbl_register_username_logo, java.awt.BorderLayout.PAGE_START);

        register_username.add(register_username_logo, java.awt.BorderLayout.CENTER);

        register_screen.add(register_username, "username");

        register_password.setOpaque(false);
        register_password.setLayout(new java.awt.BorderLayout());

        register_password_input.setBackground(new java.awt.Color(20, 20, 22));
        register_password_input.setOpaque(false);
        register_password_input.setPreferredSize(new java.awt.Dimension(500, 500));
        register_password_input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register_password_label_check.setForeground(new java.awt.Color(165, 165, 172));
        register_password_label_check.setText("Yeniden Şifre");
        register_password_input.add(register_password_label_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        register_field_password.setBackground(new java.awt.Color(20, 20, 22));
        register_field_password.setForeground(new java.awt.Color(255, 255, 255));
        register_field_password.setBorder(null);
        register_password_input.add(register_field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 220, 40));

        register_seperator_password.setBackground(new java.awt.Color(25, 25, 28));
        register_seperator_password.setForeground(new java.awt.Color(25, 25, 28));
        register_password_input.add(register_seperator_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 220, 40));

        pnl_register_password_arrow.setBackground(new java.awt.Color(30, 29, 32));
        pnl_register_password_arrow.setOpaque(false);
        pnl_register_password_arrow.setLayout(new java.awt.BorderLayout());

        lbl_register_password_arrow.setBackground(new java.awt.Color(30, 29, 32));
        lbl_register_password_arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_password_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/right-arrow.png"))); // NOI18N
        lbl_register_password_arrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_register_password_arrow.add(lbl_register_password_arrow, java.awt.BorderLayout.CENTER);

        register_password_input.add(pnl_register_password_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 60, 110));
        register_password_input.add(pnl_progress_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1370, 70));

        register_field_password_check.setBackground(new java.awt.Color(20, 20, 22));
        register_field_password_check.setForeground(new java.awt.Color(255, 255, 255));
        register_field_password_check.setBorder(null);
        register_password_input.add(register_field_password_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 220, 40));

        register_seperator_password_check.setBackground(new java.awt.Color(25, 25, 28));
        register_seperator_password_check.setForeground(new java.awt.Color(25, 25, 28));
        register_password_input.add(register_seperator_password_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 220, 40));

        register_password_label.setForeground(new java.awt.Color(165, 165, 172));
        register_password_label.setText("Şifre");
        register_password_input.add(register_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        register_password.add(register_password_input, java.awt.BorderLayout.PAGE_END);

        register_password_logo.setOpaque(false);
        register_password_logo.setLayout(new java.awt.BorderLayout());

        lbl_register_password_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_password_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/vblogowhite.png"))); // NOI18N
        lbl_register_password_logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lbl_register_password_logo.setPreferredSize(new java.awt.Dimension(300, 300));
        register_password_logo.add(lbl_register_password_logo, java.awt.BorderLayout.PAGE_START);

        register_password.add(register_password_logo, java.awt.BorderLayout.CENTER);

        register_screen.add(register_password, "password");

        register_panel.add(register_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        background2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/mailbackground.png"))); // NOI18N
        background2.setPreferredSize(new java.awt.Dimension(1366, 768));
        register_panel.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1370, 860));

        register_card.add(register_panel, java.awt.BorderLayout.CENTER);

        cardPanel.add(register_card, "register");

        login_card.setLayout(new java.awt.BorderLayout());

        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_screen.setOpaque(false);
        login_screen.setLayout(new java.awt.BorderLayout());

        login_logo_panel.setOpaque(false);
        login_logo_panel.setPreferredSize(new java.awt.Dimension(300, 300));
        login_logo_panel.setLayout(new java.awt.BorderLayout());

        login_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/vblogowhite.png"))); // NOI18N
        login_logo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        login_logo.setPreferredSize(new java.awt.Dimension(300, 300));
        login_logo_panel.add(login_logo, java.awt.BorderLayout.PAGE_START);

        login_screen.add(login_logo_panel, java.awt.BorderLayout.CENTER);

        login_inputs.setBackground(new java.awt.Color(20, 20, 22));
        login_inputs.setOpaque(false);
        login_inputs.setPreferredSize(new java.awt.Dimension(500, 500));
        login_inputs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator_username.setBackground(new java.awt.Color(25, 25, 28));
        separator_username.setForeground(new java.awt.Color(25, 25, 28));
        login_inputs.add(separator_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 220, 40));

        login_username_label.setForeground(new java.awt.Color(165, 165, 172));
        login_username_label.setText("Kullanıcı Adı");
        login_inputs.add(login_username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        login_password_label.setForeground(new java.awt.Color(165, 165, 172));
        login_password_label.setText("Şifre");
        login_inputs.add(login_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        login_field_username.setBackground(new java.awt.Color(20, 20, 22));
        login_field_username.setForeground(new java.awt.Color(255, 255, 255));
        login_field_username.setBorder(null);
        login_inputs.add(login_field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 220, 40));

        login_field_password.setBackground(new java.awt.Color(20, 20, 22));
        login_field_password.setForeground(new java.awt.Color(255, 255, 255));
        login_field_password.setBorder(null);
        login_inputs.add(login_field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 220, 40));

        separator_password.setBackground(new java.awt.Color(25, 25, 28));
        separator_password.setForeground(new java.awt.Color(25, 25, 28));
        login_inputs.add(separator_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 220, 40));

        pnl_login_arrow.setBackground(new java.awt.Color(30, 29, 32));
        pnl_login_arrow.setOpaque(false);
        pnl_login_arrow.setLayout(new java.awt.BorderLayout());

        lbl_login_arrow.setBackground(new java.awt.Color(30, 29, 32));
        lbl_login_arrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login_arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/right-arrow.png"))); // NOI18N
        lbl_login_arrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_login_arrow.add(lbl_login_arrow, java.awt.BorderLayout.CENTER);

        login_inputs.add(pnl_login_arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 60, 140));

        login_screen.add(login_inputs, java.awt.BorderLayout.PAGE_END);

        login_panel.add(login_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        background3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vbteam/views/images/mailbackground.png"))); // NOI18N
        background3.setPreferredSize(new java.awt.Dimension(1366, 768));
        login_panel.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1370, 860));

        login_card.add(login_panel, java.awt.BorderLayout.CENTER);

        cardPanel.add(login_card, "login");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTestAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTestAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTestAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTestAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTestAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel home_Buttons;
    private javax.swing.JPanel home_Logo;
    private javax.swing.JPanel home_card;
    private javax.swing.JLabel home_logo;
    private javax.swing.JPanel home_panel;
    private javax.swing.JPanel home_screen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_login_arrow;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_register_password_arrow;
    private javax.swing.JLabel lbl_register_password_logo;
    private javax.swing.JLabel lbl_register_username_arrow;
    private javax.swing.JLabel lbl_register_username_logo;
    private javax.swing.JPanel login_card;
    private javax.swing.JPasswordField login_field_password;
    private javax.swing.JTextField login_field_username;
    private javax.swing.JPanel login_inputs;
    private javax.swing.JLabel login_logo;
    private javax.swing.JPanel login_logo_panel;
    private javax.swing.JPanel login_panel;
    private javax.swing.JLabel login_password_label;
    private javax.swing.JPanel login_screen;
    private javax.swing.JLabel login_username_label;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_login_arrow;
    private javax.swing.JPanel pnl_progress;
    private javax.swing.JPanel pnl_progress_password;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JPanel pnl_register_password_arrow;
    private javax.swing.JPanel pnl_register_username_arrow;
    private javax.swing.JPanel register_card;
    private javax.swing.JTextField register_field_password;
    private javax.swing.JTextField register_field_password_check;
    private javax.swing.JTextField register_field_username;
    private javax.swing.JPanel register_panel;
    private javax.swing.JPanel register_password;
    private javax.swing.JPanel register_password_input;
    private javax.swing.JLabel register_password_label;
    private javax.swing.JLabel register_password_label_check;
    private javax.swing.JPanel register_password_logo;
    private javax.swing.JPanel register_screen;
    private javax.swing.JSeparator register_seperator_password;
    private javax.swing.JSeparator register_seperator_password_check;
    private javax.swing.JSeparator register_seperator_username;
    private javax.swing.JPanel register_username;
    private javax.swing.JPanel register_username_input;
    private javax.swing.JLabel register_username_label;
    private javax.swing.JPanel register_username_logo;
    private javax.swing.JSeparator separator_password;
    private javax.swing.JSeparator separator_username;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent evt) {
        if (evt.getSource() == pnl_login) {
            mainLayout.show(cardPanel, "login");
        }
        if (evt.getSource() == pnl_register) {
            mainLayout.show(cardPanel, "register");
        }
        if(evt.getSource() == pnl_register_username_arrow){
            registerLayout.show(register_screen,"password");
        }
    }

    @Override
    public void mousePressed(MouseEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent evt) {
        if (evt.getSource() == pnl_login || evt.getSource() == pnl_register || evt.getSource() == pnl_login_arrow || evt.getSource() == pnl_register_username_arrow) {
            JPanel panel = (JPanel) evt.getSource();
            panel.setOpaque(true);
            repaint();
        }

    }

    @Override
    public void mouseExited(MouseEvent evt) {
        if (evt.getSource() == pnl_login || evt.getSource() == pnl_register || evt.getSource() == pnl_login_arrow || evt.getSource() == pnl_register_username_arrow) {
            JPanel panel = (JPanel) evt.getSource();
            panel.setOpaque(false);
            repaint();
        }
    }
}
